"""Initial migration

Revision ID: 8ff0a02cf4c1
Revises: 
Create Date: 2024-01-10 15:19:51.699190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff0a02cf4c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_post',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('body', sa.JSON(), nullable=False),
        sa.Column('posted', sa.Boolean(), nullable=True),
        sa.Column('date_posted', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_post')
    # ### end Alembic commands ###
